#apiVersion: v1
#kind: Service
#metadata:
  #name: valaxy-service
  #labels:
    #app: valaxy-devops-project
#spec:
  #selector:
    #app: valaxy-devops-project
  #type: LoadBalancer
  #ports:
    #- port: 8080
      #targetPort: 8080
      #nodePort: 31200
#######========================================================================  
      
      apiVersion: v1
kind: Service
metadata:
  name: k8s-service
  labels:
    app: k8s-devops-project1
spec:
  selector:
    app: k8s-devops-project1
  type: LoadBalancer
  ports:
    - port: 8080
      targetPort: 8080
      nodePort: 31200
